#! /bin/sh

# This will assure that the Docker version inside the container is the
# same as the one outside. Works as long as lxc-docker is used.
docker_version=$(docker --version | sed 's_.*\([0-9]\.[0-9]\.[0-9]\).*_\1_')
line=$(cat ./Dockerfile | grep -e 'apt-get install.*lxc-docker')
new_line=$(echo $line | sed "s@\(install [-a-zA-Z]* lxc-docker\)@\1-$docker_version@")
new_line=$(echo $new_line | sed 's_&_\\&_g')
mv Dockerfile Dockerfile.bak
cat Dockerfile.bak | sed "s/$line/$new_line/" > Dockerfile
